module.exports = {
  // laws: [Law!]!
  // law(id: ID!): Law
  // lawTranslates: [LawTranslate!]!
  // lawTranslate(id: ID!): LawTranslate
  // lawTags: [LawTag!]!
  // lawTag(id: ID!): LawTag
  // lawTagTranslates: [LawTagTranslate!]!
  // lawTagTranslate(id: ID!): LawTagTranslate
  Nation: {
    jurisdictions: (parent, args, context, info) => parent.getJurisdictions(),
    contacts: (parent, args, context, info) => parent.getContacts(),
  },
  Jurisdiction: {
    nation: (parent, args, context, info) => parent.getNation(),
    contacts: (parent, args, context, info) => parent.getContacts(),
  },
  Contact: {
    nation: (parent, args, context, info) => parent.getNation(),
    jurisdiction: (parent, args, context, info) => parent.getJurisdiction(),
  },
  Query: {
    // launches: (_, __, { dataSources }) =>
    //   dataSources.launchAPI.getAllLaunches(),
    // launch: (_, { id }, { dataSources }) =>
    //   dataSources.launchAPI.getLaunchById({ launchId: id }),
    // me: (_, __, { dataSources }) => dataSources.userAPI.findOrCreateUser()
    region: (_, { id }, { dataSources }) => dataSources.regionAPI.getRegionById({ regionId: id }),
    nation: (_, { id }, { dataSources }) => dataSources.nationAPI.getNationById({ nationId: id }),
    jurisdiction: (_, { id }, { dataSources }) => dataSources.jurisdictionAPI.getJurisdictionById({ jurisdictionId: id }),
    jurisdictionByName: (_, { name }, { dataSources }) => dataSources.jurisdictionAPI.getJurisdictionByName({ name: name }),
    languages: (_, __, { dataSources }) => dataSources.languageAPI.getAllLanguages(),
    language: (_, { code }, { dataSources }) => dataSources.languageAPI.getLanguageByCode({ languageCode: code }),
    citations: (_, __, { dataSources }) => dataSources.citationAPI.getAllCitations(),
    citation: (_, { id }, { dataSources }) => dataSources.citationAPI.getCitationByCode({ citationId: id }),
    contacts: (_, __, { dataSources }) => dataSources.contactAPI.getAllContacts(),
    contact: (_, { id }, { dataSources }) => dataSources.contactAPI.getContactById({ contactId: id }),
    // partnerships: (_, __, { dataSources }) => dataSources.partnershipsAPI.getAllPartnerships(),
    // partnership: (_, { id }, { dataSources }) => dataSources.partnershipAPI.getPartnershipById({ partnershipId: id }),
    // partnershipTranslates: (_, __, { dataSources }) => dataSources.partnershipTranslatesAPI.getAllPartnershipTranslates(),
    // partnershipTranslate: (_, { id }, { dataSources }) => dataSources.partnershipTranslateAPI.getPartnershipTranslateById({ partnershipTranslateId: id }),
    // institutionalFrameworks: (_, __, { dataSources }) => dataSources.institutionalFrameworksAPI.getAllInstitutionalFrameworks(),
    // institutionalFramework: (_, { id }, { dataSources }) => dataSources.institutionalFrameworkAPI.getInstitutionalFrameworkById({ institutionalFrameworkId: id }),
    // institutionalFrameworkTranslates: (_, __, { dataSources }) => dataSources.institutionalFrameworkTranslatesAPI.getAllInstitutionalFrameworkTranslates(),
    // institutionalFrameworkTranslate: (_, { id }, { dataSources }) => dataSources.institutionalFrameworkTranslateAPI.getInstitutionalFrameworkTranslateById({ institutionalFrameworkTranslateId: id }),
    laws: (_, __, { dataSources }) => dataSources.lawsAPI.getAllLaws(),
    law: (_, { id }, { dataSources }) => dataSources.lawAPI.getLawById({ lawId: id }),
    lawTranslates: (_, __, { dataSources }) => dataSources.lawTranslatesAPI.getAllLawTranslates(),
    lawTranslate: (_, { id }, { dataSources }) => dataSources.lawTranslateAPI.getLawTranslateById({ lawTranslateId: id }),
    // safeguards: (_, __, { dataSources }) => dataSources.safeguardsAPI.getAllSafeguards(),
    // safeguard: (_, { id }, { dataSources }) => dataSources.safeguardAPI.getSafeguardById({ safeguardId: id }),
    // safeguardTranslates: (_, __, { dataSources }) => dataSources.safeguardTranslatesAPI.getAllSafeguardTranslates(),
    // safeguardTranslate: (_, { id }, { dataSources }) => dataSources.safeguardTranslateAPI.getSafeguardTranslateById({ safeguardTranslateId: id }),
    // zoningSpatialPlans: (_, __, { dataSources }) => dataSources.zoningSpatialPlansAPI.getAllZoningSpatialPlans(),
    // zoningSpatialPlan: (_, { id }, { dataSources }) => dataSources.zoningSpatialPlanAPI.getZoningSpatialPlanById({ zoningSpatialPlanId: id }),
    // zoningSpatialPlanTranslates: (_, __, { dataSources }) => dataSources.zoningSpatialPlanTranslatesAPI.getAllZoningSpatialPlanTranslates(),
    // zoningSpatialPlanTranslate: (_, { id }, { dataSources }) => dataSources.zoningSpatialPlanTranslateAPI.getZoningSpatialPlanTranslateById({ zoningSpatialPlanTranslateId: id }),
    // vegetations: (_, __, { dataSources }) => dataSources.vegetationsAPI.getAllVegetations(),
    // vegetation: (_, { id }, { dataSources }) => dataSources.vegetationAPI.getVegetationById({ vegetationId: id }),
    // forestManagements: (_, __, { dataSources }) => dataSources.forestManagementsAPI.getAllForestManagements(),
    // forestManagement: (_, { id }, { dataSources }) => dataSources.forestManagementAPI.getForestManagementById({ forestManagementId: id }),
    // deforestationRates: (_, __, { dataSources }) => dataSources.deforestationRatesAPI.getAllDeforestationRates(),
    // deforestationRate: (_, { id }, { dataSources }) => dataSources.deforestationRateAPI.getDeforestationRateById({ deforestationRateId: id }),
    // socialGroups: (_, __, { dataSources }) => dataSources.socialGroupsAPI.getAllSocialGroups(),
    // socialGroup: (_, { id }, { dataSources }) => dataSources.socialGroupAPI.getSocialGroupById({ socialGroupId: id }),
    // urbanVsRurals: (_, __, { dataSources }) => dataSources.urbanVsRuralsAPI.getAllUrbanVsRurals(),
    // urbanVsRural: (_, { id }, { dataSources }) => dataSources.urbanVsRuralAPI.getUrbanVsRuralById({ urbanVsRuralId: id }),
    // gdpCategorys: (_, __, { dataSources }) => dataSources.gdpCategorysAPI.getAllGdpCategorys(),
    // gdpCategory: (_, { id }, { dataSources }) => dataSources.gdpCategoryAPI.getGdpCategoryById({ gdpCategoryId: id }),
    // valueNationals: (_, __, { dataSources }) => dataSources.valueNationalsAPI.getAllValueNationals(),
    // valueNational: (_, { id }, { dataSources }) => dataSources.valueNationalAPI.getValueNationalById({ valueNationalId: id }),
    // valueJurisdictionals: (_, __, { dataSources }) => dataSources.valueJurisdictionalsAPI.getAllValueJurisdictionals(),
    // valueJurisdictional: (_, { id }, { dataSources }) => dataSources.valueJurisdictionalAPI.getValueJurisdictionalById({ valueJurisdictionalId: id }),
    // valueGlobals: (_, __, { dataSources }) => dataSources.valueGlobalsAPI.getAllValueGlobals(),
    // valueGlobal: (_, { id }, { dataSources }) => dataSources.valueGlobalAPI.getValueGlobalById({ valueGlobalId: id }),
    // majorExports: (_, __, { dataSources }) => dataSources.majorExportsAPI.getAllMajorExports(),
    // majorExport: (_, { id }, { dataSources }) => dataSources.majorExportAPI.getMajorExportById({ majorExportId: id }),
    // commoditys: (_, __, { dataSources }) => dataSources.commoditysAPI.getAllCommoditys(),
    // commodity: (_, { id }, { dataSources }) => dataSources.commodityAPI.getCommodityById({ commodityId: id }),
    // slrtScores: (_, __, { dataSources }) => dataSources.slrtScoresAPI.getAllSlrtScores(),
    // slrtScore: (_, { id }, { dataSources }) => dataSources.slrtScoreAPI.getSlrtScoreById({ slrtScoreId: id }),
    // organizations: (_, __, { dataSources }) => dataSources.organizationsAPI.getAllOrganizations(),
    // organization: (_, { id }, { dataSources }) => dataSources.organizationAPI.getOrganizationById({ organizationId: id }),
    // organizationTranslates: (_, __, { dataSources }) => dataSources.organizationTranslatesAPI.getAllOrganizationTranslates(),
    // organizationTranslate: (_, { id }, { dataSources }) => dataSources.organizationTranslateAPI.getOrganizationTranslateById({ organizationTranslateId: id }),
    // contentNationals: (_, __, { dataSources }) => dataSources.contentNationalsAPI.getAllContentNationals(),
    // contentNational: (_, { id }, { dataSources }) => dataSources.contentNationalAPI.getContentNationalById({ contentNationalId: id }),
    // contentNationalTranslates: (_, __, { dataSources }) => dataSources.contentNationalTranslatesAPI.getAllContentNationalTranslates(),
    // contentNationalTranslate: (_, { id }, { dataSources }) => dataSources.contentNationalTranslateAPI.getContentNationalTranslateById({ contentNationalTranslateId: id }),
    // contentJurisdictionals: (_, __, { dataSources }) => dataSources.contentJurisdictionalsAPI.getAllContentJurisdictionals(),
    // contentJurisdictional: (_, { id }, { dataSources }) => dataSources.contentJurisdictionalAPI.getContentJurisdictionalById({ contentJurisdictionalId: id }),
    // contentJurisdictionalTranslates: (_, __, { dataSources }) => dataSources.contentJurisdictionalTranslatesAPI.getAllContentJurisdictionalTranslates(),
    // contentJurisdictionalTranslate: (_, { id }, { dataSources }) => dataSources.contentJurisdictionalTranslateAPI.getContentJurisdictionalTranslateById({ contentJurisdictionalTranslateId: id }),
    // vegetationTranslates: (_, __, { dataSources }) => dataSources.vegetationTranslatesAPI.getAllVegetationTranslates(),
    // vegetationTranslate: (_, { id }, { dataSources }) => dataSources.vegetationTranslateAPI.getVegetationTranslateById({ vegetationTranslateId: id }),
    // socialGroupTranslates: (_, __, { dataSources }) => dataSources.socialGroupTranslatesAPI.getAllSocialGroupTranslates(),
    // socialGroupTranslate: (_, { id }, { dataSources }) => dataSources.socialGroupTranslateAPI.getSocialGroupTranslateById({ socialGroupTranslateId: id }),
    // gdpCategoryTranslates: (_, __, { dataSources }) => dataSources.gdpCategoryTranslatesAPI.getAllGdpCategoryTranslates(),
    // gdpCategoryTranslate: (_, { id }, { dataSources }) => dataSources.gdpCategoryTranslateAPI.getGdpCategoryTranslateById({ gdpCategoryTranslateId: id }),
    // commodityTranslates: (_, __, { dataSources }) => dataSources.commodityTranslatesAPI.getAllCommodityTranslates(),
    // commodityTranslate: (_, { id }, { dataSources }) => dataSources.commodityTranslateAPI.getCommodityTranslateById({ commodityTranslateId: id }),
    // exportTranslates: (_, __, { dataSources }) => dataSources.exportTranslatesAPI.getAllExportTranslates(),
    // exportTranslate: (_, { id }, { dataSources }) => dataSources.exportTranslateAPI.getExportTranslateById({ exportTranslateId: id }),
    lawTags: (_, __, { dataSources }) => dataSources.lawTagsAPI.getAllLawTags(),
    lawTag: (_, { id }, { dataSources }) => dataSources.lawTagAPI.getLawTagById({ lawTagId: id }),
    lawTagTranslates: (_, __, { dataSources }) => dataSources.lawTagTranslatesAPI.getAllLawTagTranslates(),
    lawTagTranslate: (_, { id }, { dataSources }) => dataSources.lawTagTranslateAPI.getLawTagTranslateById({ lawTagTranslateId: id }),
  }
};
